name: Deployment

on:
  pull_request:
  push:
    branches:
      ["**"]
jobs:
  Deploy:
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - name: `Run deployment on main`
        run: docker compose up -d